Cu 29wjh43/add age gate to free 1on1s
skills-annex/calendso pull request #69
Opened 2022-05-06 23:30 UTC by bashby44

## What does this PR do?
Adds age gate to 1on1 

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code and corrected any misspellings
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-05-06 23:30 UTC, mcasey8540 commented
Task linked: [CU-29wjh43 Add age gate to free 1on1s](https://app.clickup.com/t/29wjh43)

2022-05-09 14:14 UTC, zach-at-the-skills requested changes
One question, otherwise the code looks great!

2022-05-09 14:14 UTC, zach-at-the-skills commented on components/booking/pages/BookingPage.tsx
> +      await updateContact({
Don't we want to send this to hubspot regardless of if it is free or not?

2022-05-09 15:19 UTC, zach-at-the-skills approved these changes

2022-05-09 19:42 UTC, zach-at-the-skills approved these changes

2022-05-09 19:54 UTC, merged